In [2]:
import pandas as pd

# 전체파일 통합

In [3]:
df = pd.DataFrame()

In [4]:
for i in range(80):
    file_path = 'C:/DEV/STUDY/StudyPython22.06/day8/data/trfcard({}).csv'.format(i)
    df_temp = pd.read_csv(file_path)
    df = pd.concat([df,df_temp], ignore_index=True)

In [5]:
# 결측치 체크
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842608 entries, 0 to 842607
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   on_date      842608 non-null  int64
 1   off_date     842608 non-null  int64
 2   route_name   842608 non-null  object
 3   descr        842608 non-null  object
 4   age_type     842608 non-null  object
 5   trans_yn     842608 non-null  object
 6   addfee_yn    842608 non-null  object
 7   start_bstop  842608 non-null  object
 8   start_gps_x  842608 non-null  float64
 9   start_gps_y  842608 non-null  float64
 10  end_bstop    842608 non-null  object
 11  end_gps_x    842608 non-null  float64
 12  end_gps_y    842608 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 83.6+ MB

In [6]:
# 이상치 체크
df.describe()

,on_date,off_date,start_gps_x,start_gps_y,end_gps_x,end_gps_y
count,8.426080e+05,8.426080e+05,842608.000000,842608.000000,842608.000000,842608.000000
mean,2.020017e+13,2.020017e+13,129.369875,36.033987,129.369699,36.030874
std,6.691819e+07,6.691830e+07,0.051007,0.044272,0.042348,0.034512
min,2.020010e+13,2.020010e+13,129.025585,35.804119,129.025585,35.804119
25%,2.020012e+13,2.020012e+13,129.350290,36.010240,129.353856,36.013250
50%,2.020013e+13,2.020013e+13,129.365486,36.031170,129.365281,36.033732
75%,2.020022e+13,2.020022e+13,129.384770,36.064088,129.371682,36.045735
max,2.020033e+13,2.020040e+13,129.579045,36.303479,129.579045,36.303479

In [7]:
# 중복값 체크
df.duplicated().sum()

0

# 컬럼명 한글로 변환

In [8]:
file_path = 'C:/DEV/STUDY/StudyPython22.06/day8/data/데이터_정의서.xlsx'
col_kor_name = pd.read_excel(file_path,
                             header=11,
                             usecols='A,B')
col_kor_name

        컬럼명(영문)         컬럼 설명
0       on_date          승차시각
1      off_date          하차시각
2    route_name           노선명
3         descr          노선설명
4      age_type          승객연령
5      trans_yn          환승여부
6     addfee_yn        추가운임여부
7   start_bstop         승차정류장
8   start_gps_x   승차정류장 GPS X
9   start_gps_y   승차정류장 GPS Y
10    end_bstop         하차정류장
11    end_gps_x   하차정류장 GPS X
12    end_gps_y   하차정류장 GPS Y

In [9]:
col_kor_name_list = col_kor_name.to_dict('records')
col_kor_name_list

[{'컬럼명(영문)': 'on_date', '컬럼 설명': ' 승차시각'},
 {'컬럼명(영문)': 'off_date', '컬럼 설명': ' 하차시각'},
 {'컬럼명(영문)': 'route_name', '컬럼 설명': ' 노선명'},
 {'컬럼명(영문)': 'descr', '컬럼 설명': ' 노선설명'},
 {'컬럼명(영문)': 'age_type', '컬럼 설명': ' 승객연령'},
 {'컬럼명(영문)': 'trans_yn', '컬럼 설명': ' 환승여부'},
 {'컬럼명(영문)': 'addfee_yn', '컬럼 설명': ' 추가운임여부'},
 {'컬럼명(영문)': 'start_bstop', '컬럼 설명': ' 승차정류장'},
 {'컬럼명(영문)': 'start_gps_x', '컬럼 설명': ' 승차정류장 GPS X'},
 {'컬럼명(영문)': 'start_gps_y', '컬럼 설명': ' 승차정류장 GPS Y'},
 {'컬럼명(영문)': 'end_bstop', '컬럼 설명': ' 하차정류장'},
 {'컬럼명(영문)': 'end_gps_x', '컬럼 설명': ' 하차정류장 GPS X'},
 {'컬럼명(영문)': 'end_gps_y', '컬럼 설명': ' 하차정류장 GPS Y'}]

In [10]:
# 깨끗한 딕셔너리 변수 생성
new_dict = {}

In [11]:
for i in col_kor_name_list:
    value, key = i.values()
    new_dict[key] = value
    
df_kor = df.rename(columns=new_dict)
df_kor

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y
0,20200104051524,20200104052439,131,양덕-송도-시청-양학-양덕,일반,N,N,양덕차고지,129.401693,36.077258,죽도시장,129.365486,36.034110
1,20200104051607,20200104053502,500,문덕-시외터미널-흥해-청하-월포,일반,N,N,문덕사거리,129.403442,35.962846,시외버스터미널,129.350580,36.013250
2,20200104051838,20200104052941,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,N,N,준양주택3차,129.403063,35.960871,청림초등학교,129.405275,35.993257
3,20200104052127,20200104052430,200,양덕-남구청(야구장)-구룡포,청소년,N,N,환호해맞이그린빌,129.392404,36.068838,두호동주민센터,129.378910,36.060370
4,20200104052229,20200104053228,108,양덕-죽도-양학-시청-유강-지곡,일반,N,N,장량휴먼시아,129.383462,36.090800,두호초등학교,129.371202,36.064088
...,...,...,...,...,...,...,...,...,...,...,...,...,...
842603,20200103234051,20200103234410,107,문덕-시외(고속)터미널-흥해,일반,N,N,도심환승센터,129.365165,36.043435,죽도시장,129.365486,36.034110
842604,20200103234140,20200103234229,109,양덕-시외터미널-위덕대(유강),일반,Y,N,대동우방아파트,129.360148,36.050620,동아화성아파트,129.356090,36.051290
842605,20200103234616,20200103235557,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,N,N,대도교회,129.356060,36.009820,우리유치원,129.410930,35.982500
842606,20200103234845,20200104000712,108,양덕-죽도-양학-시청-유강-지곡,일반,N,N,우방신천지타운,129.370103,36.058736,경성홈타운,129.385980,36.077010
842607,20200103234927,20200103235821,109,양덕-시외터미널-위덕대(유강),일반,N,N,장성초등학교,129.372370,36.068290,상지프라자,129.393115,36.081740

In [12]:
df_kor.to_csv('C:/DEV/STUDY/StudyPython22.06/day8/data/trfcard_result.csv', index=False)